### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MikeB2019x** [geronimo-iia/networkx-query#2]
Will networkx-query accommodate longer paths?  For example, I want to query all paths A->B->C->D where A-D are nodes with a particular attribute.  I haven't read the code yet but my impression from the examples is 'no'.  TIA

**Comment by geronimo-iia** [comment]
sorry, i havent see your question... 

I havent worked on path lookup, but you could select your specific nodes A and D, and  use https://networkx.org/documentation/networkx-1.9/reference/generated/networkx.algorithms.simple_paths.all_simple_paths.html.

**Comment by MikeB2019x** [comment]
Tnx!  Simple paths works for some cases but I was thinking a case where each node is say, of a specific type.  It would be like specifying a template path e.g. Type-A -> Type-B -> Type C.  So only paths following that specificy progression ie. Type-A -> Type-E -> Type-C would not be a valid path.

**Comment by geronimo-iia** [comment]
I see what you mean, I had to look a little bit inside networkx project api and how handle this case. 
We could also extends this case to Type-A -> n -> Type-B -> m-> Type C, with more or less node between those which wear constraints.
Very interesting :)

**Comment by geronimo-iia** [comment]
First test and result:
`
g = nx.DiGraph()
g.add_node(1, product="a")
g.add_node(2, product="b")
g.add_node(3, product="c")
g.add_node(4, product="d")

g.add_edge(1, 2)
g.add_edge(1, 3)
g.add_edge(1, 4)

g.add_edge(2, 4)
g.add_edge(3, 4)




for p in search_relationships(
    g, 
    {"eq": [("product",), "a"]}, 
    PathCriteria(target={"eq": [("product",), "b"]}),
    PathCriteria(target={"eq": [("product",), "d"]})
):
    print(p)
`

output: [1, 2, 4]

I will add more test unit and doc on it asap :)

**Comment by geronimo-iia** [comment]
add https://github.com/geronimo-iia/networkx-query/pull/5

**Comment by geronimo-iia** [comment]
v1.0.3 released
