### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by jlaumonier** [geronimo-iia/networkx-query#44]
The version 2.0.1 of the package explicitly excludes python 3.12 which begins to be a problem since some distributions (manjaro and ubuntu 24.04 and maybe others) use python 3.12 as the main version.

For information, i tested the package (not extensively, using search_direct_relationships, search_nodes, search_relationships and PathCriteria) with python 3.12 just by removing the <3.12 in pyproject.toml from the last github commit and it seems to be working.

Do you plan to release a new version soon which supports python 3.12 ?

Thank you by advance

**Comment by geronimo-iia** [comment]
Hello, thanks for the reminder, yes I must do!
I didn't remember why I excluded this version (maybe a dependency
problems...) I will do some changes very soon (I'm in vacation for now)

Regards

**Comment by jlaumonier** [comment]
Thanks ! No rush, especially if you are in vacation :)

**Comment by geronimo-iia** [comment]
Support in on his way : https://github.com/geronimo-iia/networkx-query/pull/46

**Comment by geronimo-iia** [comment]
New version is 2.1.0 is availaible, https://pypi.org/project/networkx_query/


https://github.com/geronimo-iia/networkx-query/releases/tag/v2.1.0
